FROM confluentinc/cp-kafka-connect-base:7.6.1 AS es-plugin
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:latest

FROM debezium/connect:2.6

USER root

COPY --from=es-plugin \
    /usr/share/confluent-hub-components/confluentinc-kafka-connect-elasticsearch \
    /kafka/connect/confluentinc-kafka-connect-elasticsearch

USER kafka
